spring:
  datasource:
     url: jdbc:postgresql://10.110.18.6:5432/pollute
     username: postgres
     password: postgres@123
     driver-class-name: org.postgresql.Driver
#配置时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
#修改默认上传文件大小设置
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 1200MB
#kafka配置信息
  kafka:
    #Kafka服务器地址
    bootstrap-servers: 106.112.143.254:49092
    consumer:
      #设置数据value的反序列化处理类
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: test-consumer-group

server:
  port: 10002
logging:
  level:
    com:
      threeclear:
        pollution:
          dao: debug
mybatis-plus:
  global-config:
    db-config:
      select-strategy: not_empty
phase:
  url: http://106.112.143.254:63125/IntelligentSchedulingBack/event/info/process?taskCode=
report:
  url: http://106.112.143.254:63125/IntelligentSchedulingBack/task/flow/device/report
base:
  path: /home/ssta/file/
ftp:
  config:
    ip: 10.122.88.227
    port: 6079
    user: ftpd
    pwd: tYhJe#1xki





